name: PEP8 Lint

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: ubuntu-latest # specify your self-hosted runner here
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Review files with Flake8
      run: |
        flake8 ${{ steps.files.outputs.files }}  --max-line-length=120 .
